version: "3.4"

services:
  rockets-starter:
    image: rockets-starter
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/workspace:delegated
    environment:
      NODE_ENV: development
    ports:
      - 3001:3001
    links:
      - rockets-starter-postgres

  rockets-starter-postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
